version: "3.8"

services:
  manipulator:
    build: manipulator/
    ports:
      - 5000:5000

  controller:
    build: controller/
    ports:
      - 8000:8000
    depends_on:
        - manipulator

  common:
    build: sensors/
    ports:
      - 8081:8081
    command:
      - common
    restart: always
    depends_on:
      - controller

  random:
    build: sensors/
    ports:
      - 8080:8080
    command:
      - random
    restart: always
    depends_on:
      - controller

  temperature:
    build: sensors/
    ports:
      - 8082:8082
    command:
      - temperature
    restart: always
    depends_on:
      - controller

  humidity:
    build: sensors/
    ports:
      - 8083:8083
    command:
      - humidity
    restart: always
    depends_on:
      - controller

  time:
    build: sensors/
    ports:
      - 8084:8084
    command:
      - time
    restart: always
    depends_on:
      - controller

  condition:
    build: sensors/
    ports:
      - 8085:8085
    command:
      - condition
    restart: always
    depends_on:
      - controller


  population:
    build: sensors/
    ports:
      - 8086:8086
    command:
      - population
    restart: always
    depends_on:
      - controller


  season:
    build: sensors/
    ports:
      - 8087:8087
    command:
      - season
    restart: always
    depends_on:
      - controller

networks:
    task:
        driver: bridge
